services:
  postgres:
    image: postgres:15-alpine
    container_name: sqlia-postgres
    environment:
      POSTGRES_USER: sqlia_user
      POSTGRES_PASSWORD: sqlia_password
      POSTGRES_DB: sqlia_db
    ports:
      - '5432:5432'
    volumes:
      - ./.db-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: sqlia-redis
    ports:
     - '6379:6379'
    restart: unless-stopped
