export const CHALLENGE_COURSE_OWNERSHIP_QUERY = Symbol(
  'CHALLENGE_COURSE_OWNERSHIP_QUERY',
);
export const CHALLENGE_SANDBOX_EXPIRES_AT_QUERY = Symbol(
  'CHALLENGE_SANDBOX_EXPIRES_AT_QUERY',
);
export const CHALLENGE_PUBLISH_FOR_SANDBOX_COMMAND = Symbol(
  'CHALLENGE_PUBLISH_FOR_SANDBOX_COMMAND',
);
export const CHALLENGE_ARCHIVE_ON_SANDBOX_TEARDOWN_COMMAND = Symbol(
  'CHALLENGE_ARCHIVE_ON_SANDBOX_TEARDOWN_COMMAND',
);
