/**
 * Formato CSV: Brightspace Groups → Export → All Groups.
 * @see docs/CategoríaPyFlutter_AllGroups_20260217225843.csv
 * @see docs/CategoriaAleatoriaPrueba_AllGroups_20260309210227.csv
 */
export const BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS = {
  GROUP_CATEGORY_NAME: 'Group Category Name',
  GROUP_NAME: 'Group Name',
  GROUP_CODE: 'Group Code',
  USERNAME: 'Username',
  ORG_DEFINED_ID: 'OrgDefinedId',
  FIRST_NAME: 'First Name',
  LAST_NAME: 'Last Name',
  EMAIL_ADDRESS: 'Email Address',
  GROUP_ENROLLMENT_DATE: 'Group Enrollment Date',
} as const;

export const BRIGHTSPACE_ENROLLMENT_CSV_HEADER_ORDER = [
  BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.GROUP_CATEGORY_NAME,
  BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.GROUP_NAME,
  BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.GROUP_CODE,
  BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.USERNAME,
  BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.ORG_DEFINED_ID,
  BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.FIRST_NAME,
  BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.LAST_NAME,
  BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.EMAIL_ADDRESS,
  BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.GROUP_ENROLLMENT_DATE,
] as const;

export const BRIGHTSPACE_ENROLLMENT_EMAIL_COLUMN =
  BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.EMAIL_ADDRESS;

export type BrightspaceEnrollmentCsvRow = {
  [BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.GROUP_CATEGORY_NAME]: string;
  [BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.GROUP_NAME]: string;
  [BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.GROUP_CODE]: string;
  [BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.USERNAME]: string;
  [BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.ORG_DEFINED_ID]: string;
  [BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.FIRST_NAME]: string;
  [BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.LAST_NAME]: string;
  [BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.EMAIL_ADDRESS]: string;
  [BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.GROUP_ENROLLMENT_DATE]: string;
};

export const BRIGHTSPACE_ENROLLMENT_CSV_ROW_EXAMPLE: BrightspaceEnrollmentCsvRow = {
  [BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.GROUP_CATEGORY_NAME]: 'CategoriaAleatoriaPrueba',
  [BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.GROUP_NAME]: 'Group 1',
  [BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.GROUP_CODE]: 'grp_156874_9417_1',
  [BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.USERNAME]: 'almachado@uninorte.edu.co',
  [BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.ORG_DEFINED_ID]: '365008',
  [BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.FIRST_NAME]: 'LUIS',
  [BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.LAST_NAME]: 'LOPEZ MACHADO',
  [BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.EMAIL_ADDRESS]: 'almachado@uninorte.edu.co',
  [BRIGHTSPACE_ENROLLMENT_CSV_COLUMNS.GROUP_ENROLLMENT_DATE]:
    '9 de marzo de 2026 16:01',
};
